### ISSUE TITLE
Upload never completes contract deployment

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#41]
I manually killed first one, to try again but keeps just hanging. Assume the full path name to the file is required?

Will try another host in a bit.

Also the tutorial does not cover multiple hosts, my contract needs at min 3 contract instances, how does one achieve that simply repeat all the steps and deploy it on 3 hosts i assume?

<img width="657" alt="Screen Shot 2022-10-23 at 09 59 30" src="https://user-images.githubusercontent.com/508629/197393565-efc8a3dc-0256-4c24-bb2c-77ff238f05d8.png">

**Comment by lathanbritz** [comment]
tried another host as well same result, never uploads.
<img width="645" alt="Screen Shot 2022-10-23 at 11 20 59" src="https://user-images.githubusercontent.com/508629/197397346-3edf4519-1ae6-4e03-8fb2-581458295340.png">

**Comment by Udith-Gayan** [comment]
@lathanbritz We will  investigate this issue and keep you updated.

**Comment by chalith** [comment]
@lathanbritz we've now fixed this in the hpdevkit and released a new version (0.5.3). Can you update the hpdevkit and try again

**Comment by lathanbritz** [comment]
thanks @chalith ill wait then as i require the cluster.

**Comment by chalith** [comment]
@lathanbritz shall I close the issue?

**Comment by ravinsp** [comment]
@chalith I think @lathanbritz can update hpdevkit and follow our existing tutorial again. See whether the deployment works right now without waiting for our future tooling change.

**Comment by lathanbritz** [comment]
Tried another host must have been on wrong port... 

but same issue as before after updating hpdevkit, stuck at uploading never finishes.

<img width="635" alt="Screen Shot 2022-10-26 at 15 19 52" src="https://user-images.githubusercontent.com/508629/198105318-3164b011-d32b-48f8-8ac2-2443c1680769.png">

**Comment by chalith** [comment]
@lathanbritz Can you check the hpdevkit version by `hpdevkit version`?
Did you run `hpdevkit bundle ` again before uploading?
Can you send us the `contract.config` inside the bundle.zip

**Comment by lathanbritz** [comment]
```
Lathans-iMac:mycontract lathan$ hpdevkit version
command: version

0.5.3

```
Did you run `hpdevkit bundle` again before uploading? YES


Can you send us the contract.config inside the bundle.zip (zipped that file as github dont support uploading that file natively)
[contract.config.zip](https://github.com/HotPocketDev/evernode-sdk/files/9883901/contract.config.zip)

**Comment by Udith-Gayan** [comment]
We checked your contract.config file and saw that the UNL was incorrect.  
When you run the `hpdevkit bundle` command, you have to provide **the public key of the acquired instance**, which comes as a response after acquiring an instance, but not the client public key which is generated via `node myclient.js generatekeys` . 
Note: you have to provide the generated client public key in the **owner_pubkey** field in the acquire submit-request.

**Comment by Udith-Gayan** [comment]
@lathanbritz has the issue been resolved? If yes, please close the issue.

**Comment by lathanbritz** [comment]
Will try deploying this again next day or two and comment back here

**Comment by chalith** [comment]
@lathanbritz any update on the issue?

**Comment by lathanbritz** [comment]
working through this again here today,

in the docs here https://github.com/EvernodeXRPL/evernode-sdk/blob/main/evernode/tutorial-cluster.md it does not explain where one get the `EV_TENANT_SECRET `

<img width="1036" alt="Screen Shot 2022-12-15 at 14 03 53" src="https://user-images.githubusercontent.com/508629/207922852-c4494aac-28fa-41ec-8aaa-ca7cfbe79c12.png">

**Comment by ravinsp** [comment]
@lathanbritz EV_TENANT_SECRET is the secret of the XRPL account that leases an instance from an Evernode host (that's why it's called a "Tenant"). The Tenant's account should have sufficient EVR balance to pay for the least. You can generate a testnet XRPL account with EVR balance using [this page](https://github.com/EvernodeXRPL/evernode-sdk/blob/main/evernode/tutorial-cluster.md).

This is already mentioned in the tutorial steps. But please do let us know if it's unclear or misleading so we can improve the docs.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/33562092/208002299-1a6caa93-4647-4239-a2b6-70779566be5f.png">
