### ISSUE TITLE
`Cluster 'default' already exists` issue

### ISSUE THREAD

**Issue by wojake** [EvernodeXRPL/evernode-sdk#49]
![image](https://user-images.githubusercontent.com/87929946/201676153-f3aa781d-993d-45c8-a0cc-7b5d7ead4a81.png)

## Steps to reproduce
1. cd mycontract/src
2. npm start
When it's about to create the nodes' image, do:
3. Ctrl+C, to cancel it out and immediately run:
4. hpdevkit clean

This is what I did to encounter this issue.

**Comment by Udith-Gayan** [comment]
@wojake We have fixed the issue with hpdevkit clean command. Could you update the tool with `npm update hpdevkit -g` and try again ?
