### ISSUE TITLE
Thrown on Evernode Deployement RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#53]
running the contract deployment

`evdevkit cluster-create 5 . /usr/bin/node -a mycontract.js`

produces error
`/usr/local/lib/node_modules/evdevkit/node_modules/bson/lib/parser/serializer.js:253
    buffer.set(ensure_buffer_1.ensureBuffer(value), index);`

<img width="954" alt="Screen Shot 2022-12-15 at 21 58 36" src="https://user-images.githubusercontent.com/508629/207998119-85748960-0367-4863-83eb-2ba37a825b08.png">

**Comment by lathanbritz** [comment]
assume one of the config .json files that one has to export has an issue?

EV_CONTRACT_CONFIG.json 
```
{
    "contract": {
        "bin_path": "/usr/bin/node",
        "bin_args": "index.js",
        "environment": {
            "ENDPOINT": "wss://hooks-testnet-v2.xrpl-labs.com",
            "XRPL_SOURCE_ACCOUNT" : "r4DosiqK2PYcemac4ySY9B8VXP8aRzABbP",
            "XRPL_DESTINATION_ACCOUNT": "r3Z4Ky5rRKtMUP19Tpfjh1uaHRFAXZRnn5",
            "REST_EXCHANGE_TIMEOUT": "1000"
        },
        "consensus": {
            "roundtime": 4000
        }
    },
    "mesh": {
      "peer_discovery": {
            "enabled": true,
            "interval": 10000
      }
   }
}
```


EV_INSTANCE_CONFIG.json
```
{
    "consensus": {
       "roundtime": 3000
    }
}
```

**Comment by lathanbritz** [comment]
yup seems like it was just that.

updated

EV_CONTRACT_CONFIG.json to 
```
{
    "contract": {
        "environment": {
            "ENDPOINT": "wss://hooks-testnet-v2.xrpl-labs.com",
            "XRPL_SOURCE_ACCOUNT" : "r4DosiqK2PYcemac4ySY9B8VXP8aRzABbP",
            "XRPL_DESTINATION_ACCOUNT": "r3Z4Ky5rRKtMUP19Tpfjh1uaHRFAXZRnn5",
            "REST_EXCHANGE_TIMEOUT": "1000"
        },
        "consensus": {
            "roundtime": 4000
        }
    },
    "mesh": {
      "peer_discovery": {
            "enabled": true,
            "interval": 10000
      }
   }
}
```

but still getting another error
<img width="812" alt="Screen Shot 2022-12-15 at 22 14 24" src="https://user-images.githubusercontent.com/508629/207999648-78576538-7233-494c-be14-f8bf1034fe1d.png">

`Error occurred while creating the cluster: Bootstrap contact is not available: Input timeout.`

**Comment by lathanbritz** [comment]
ran it again as realised my node path was wrong but now im back to the previous error...
 
<img width="825" alt="Screen Shot 2022-12-15 at 22 24 17" src="https://user-images.githubusercontent.com/508629/208000611-d7df5463-b593-458f-9ea2-b43c67d91c10.png">

leave my feed back here and wait for comment.

**Comment by ravinsp** [comment]
@lathanbritz can you post the file size of the generated bundle.zip (file location as shown in the your console: "../bundle/bundle.zip")?

**Comment by lathanbritz** [comment]
<img width="520" alt="Screen Shot 2022-12-15 at 22 43 36" src="https://user-images.githubusercontent.com/508629/208002729-8cb7bebc-fa03-4194-92c8-513e7d811bd5.png">
its never created @ravinsp

**Comment by lathanbritz** [comment]
<img width="472" alt="Screen Shot 2022-12-15 at 22 45 08" src="https://user-images.githubusercontent.com/508629/208002916-92c1a734-35cb-409e-bc64-f5b84c5d37ed.png">
bah sorry looking wrong place

**Comment by ravinsp** [comment]
@lathanbritz at first glance, I'm suspecting whether 18MB file is too big for the bson library/protocol we are using. This is something we will have to separately investigate. However, I can see you have specified contract directory path parameter to cluster-create command (the parameter after "5") as "." (current directory). Ideally you should specify the folder path containing the build outputs of your contract, not the source code. Is that the case here or does the current directory also hold the source code (and possibly node_modules as well?)

If you used hpdevkit to generate your contract project, it is the path to the "dist" folder that you should specify here for cluster-create command.

**Comment by lathanbritz** [comment]
Fixed path issue and reduced size but still same result for me.

<img width="782" alt="Screen Shot 2022-12-15 at 23 06 47" src="https://user-images.githubusercontent.com/508629/208005546-ef3a0489-b716-403d-9600-4040b59d5e4b.png">

**Comment by lathanbritz** [comment]
YAY figured it, went back to original less all my attempts.... and that worked main issue up front was speccing the wrong dir not using `./dist` in my case

` evdevkit cluster-create 5 ./dist /usr/bin/node -a index.js`
