### ISSUE TITLE
Change ports hp hpdevkit runs on?

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#64]
<img width="1027" alt="Screen Shot 2023-04-28 at 13 13 45" src="https://user-images.githubusercontent.com/508629/235233528-be70f534-9b4f-4d87-9f63-cb855697893e.png">

To overcome building on different env in evernode im just using my server atm to build and run till i can figure out how to get ncc to compile for a different target env.

but my sever has already occupied the port and i dont find any reference to adjusting the port here https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hotpocket/reference-configuration.md

**Comment by wojake** [comment]
https://github.com/EvernodeXRPL/hp-js-client/issues/3#issuecomment-1528371440

**Comment by ravinsp** [comment]
@lathanbritz You can use following environment variables to control this: https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hpdevkit/index.md#environment-variables
