### ISSUE TITLE
anyone looking at the hp-js-client issue queue?

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#65]
seem to get a response here quickly but there a issue holding me up in the [hp-js-client](https://github.com/EvernodeXRPL/hp-js-client) issue queue.

thanks lathan, close this when found.

**Comment by ravinsp** [comment]
@lathanbritz Good way to get attention! So sorry. Probably a result of no notifications configured :-) Will address your issues in those.
