### ISSUE TITLE
`ACQUIRE_ERR` due to timeout

### ISSUE THREAD

**Issue by jremi** [EvernodeXRPL/evernode-sdk#68]
I am reading thru all of the markdowns and getting acquainted with the architecture.

Yesterday I was successfully able to acquire host leases.

Today, I have attempted to acquire specific host and also random hosts. I have made several attempts over the last few hours to re-try acquiring a host lease. 

All of my attempts are failing with 

```shell
$ evdevkit acquire
command: acquire
Picked random host rsLdDhxqcaaRbM4rqTwN75x6AKHs82xyEE
Transaction result: tesSUCCESS
Waiting for acquire response... (txHash: 06CE3C9E6888BE0CD284206DE5E7BC1C2AB9D8C45D443795B5342E2859D7B1F4)
Error occurred while acquiring the instance: { error: 'ACQUIRE_ERR', reason: 'TIMEOUT' }
```

When I look at the Evernode dashboard for the specific host that was selected via the acquire and the lease offer has been taken. 

What is the underlying cause of the `{ error: 'ACQUIRE_ERR', reason: 'TIMEOUT' }` ?

Also, i just wanted to say that this project is very inspiring. I think what you guys are building is awesome 💯  🙏

**Comment by wojake** [comment]
Tx: https://hooks-testnet-v3-explorer.xrpl-labs.com/tx/06CE3C9E6888BE0CD284206DE5E7BC1C2AB9D8C45D443795B5342E2859D7B1F4

Tenant account's URIToken holdings: https://hooks-testnet-v3-explorer.xrpl-labs.com/rHt49uZVPzC2cn8ecRYkb4wbSswhQW2PvD/objects

Your tenant account has acquired all the instance's NFT off the market (successfully), I think there's a misconfiguration with your HotPocket contract's build/image? @ravinsp knows better tho 😄

**Comment by kithminisg** [comment]
@jremi , I think the issue might be due to the `evdevkit` version on your machine. Could you please update that to the latest version (0.6.4) and re-try?

Thanks for your feedback.

**Comment by jremi** [comment]
@wojake thanks for your comment.

@kithminisg I just upgraded the `evdevkit` from **0.6.3** to the latest **0.6.4**. 

I then re-ran the `evdevkit acquire` to randomly obtain a new host lease.

Now, successful ✅  . The CLI is now returning the "Instance created!" with the instance info.

That is great!

My next question:

What is the correct procedure for releasing the host leases that I no longer want?

For example:

1. I acquire 5 host leases.... 
2. I have not yet deployed any HotPocket contracts to any of the hosts.
3. I want to now remove/destroy/release the leases from my account since I am not using them.

I do not see any CLI flag/options inside the `evdevkit` to do this... what is the best way to accomplish this?

🙏

**Comment by kithminisg** [comment]
@jremi, Actually, those leases are in a broken stage because they were purchased using the deprecated acquire protocol. As a result, the host was unable to identify them as valid acquisitions, and no instance creation took place. However, these leases will not be burnt and recreated by the software on the host machine since they are in the broken stage. That's why we recommended those hosts perform a transfer and a re-installation to generate leases freshly. Hence, those broken leases (URI Tokens) will remain in your tenant's wallet.

**Comment by jremi** [comment]
@kithminisg thanks for the information.

I did a host transfer/re-install and re-generated new leases. I will try testing deployment of a contract with the latest versions of `evdevkit`
