### ISSUE TITLE
update README to include links to newer contract examples

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#69]
I have to go fish out the tweet every time to find the links to the newer examples could the README please be updated with their links.

**Comment by ravinsp** [comment]
@lathanbritz Can you tell us which links on the readme you found to be outdated or missing? Thank you.

**Comment by lathanbritz** [comment]
https://twitter.com/evernodexrpl/status/1663662243140222976?s=46&t=Uy2NAbE9Dd1keWqb3DShWw

**Comment by ravinsp** [comment]
Well, these are already in the readme. They are in the tutorials list.

**Comment by lathanbritz** [comment]
OMG i am blind!
