### ISSUE TITLE
deployment struggling again.

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#70]
<img width="667" alt="Screen Shot 2023-06-04 at 23 51 43" src="https://github.com/EvernodeXRPL/evernode-sdk/assets/508629/640c4887-2a0c-44ee-84d7-ef303c4aedf0">
attached is my bundle...

[bundle.zip](https://github.com/EvernodeXRPL/evernode-sdk/files/11648328/bundle.zip)

**Comment by lathanbritz** [comment]
I first acquired a cluster... of 5 nodes (what i was aiming to test). Now im just trying a basic single node, but that is still getting rejected for me as well.

**Comment by chalith** [comment]
This could be due to a connection issue at that time, Can you try again deploying to the same host using deploy command `evdevkit deploy --help`

**Comment by lathanbritz** [comment]
<img width="1102" alt="Screen Shot 2023-06-05 at 08 19 44" src="https://github.com/EvernodeXRPL/evernode-sdk/assets/508629/4b3b656a-03c7-4f36-b4c5-5ec8668adba2">
<img width="1034" alt="Screen Shot 2023-06-05 at 08 13 47" src="https://github.com/EvernodeXRPL/evernode-sdk/assets/508629/d0e314d7-1c89-4f1b-951d-fd2bbbbe38ab">


no luck so far

**Comment by lathanbritz** [comment]
and here is my latest attempt, building of my ubuntu server and trying to deploy from there, as just making sure its not the issue of the build from my intel imac thats the issue....

but here im getting a different error "Bootstrap contact is not available: Error: buffer length 127 must === bson size 576486178" when trying the upload. 

![Screen Shot 2023-06-05 at 11 06 59](https://github.com/EvernodeXRPL/evernode-sdk/assets/508629/c2b39b41-d40d-49db-a4c1-6d1cbb922265)

![Screen Shot 2023-06-05 at 11 06 50](https://github.com/EvernodeXRPL/evernode-sdk/assets/508629/a9c2771a-5362-4a40-a038-cff831a56a91)

**Comment by chalith** [comment]
We'll look into this and give you an update

**Comment by chalith** [comment]
> and here is my latest attempt, building of my ubuntu server and trying to deploy from there, as just making sure its not the issue of the build from my intel imac thats the issue....
> 
> but here im getting a different error "Bootstrap contact is not available: Error: buffer length 127 must === bson size 576486178" when trying the upload.
> 
> ![Screen Shot 2023-06-05 at 11 06 50](https://user-images.githubusercontent.com/508629/243394097-a9c2771a-5362-4a40-a038-cff831a56a91.png)
> 
> ![Screen Shot 2023-06-05 at 11 06 59](https://user-images.githubusercontent.com/508629/243394078-c2b39b41-d40d-49db-a4c1-6d1cbb922265.png)

If I'm correct, In this logs it seems you first ran `cluster-create` which does the cluster creation and contract bundle upload together and it got succeeded. And then you are trying to `deploy` a bundle again to the cluster you've just created with your bundle which ended up with "Bootstrap contact is not available: Error: buffer length 127 must === bson size 576486178" error.

Since you've already replaced the bootstrap contract with your contract in `cluster-create` command. Now there's no more bootstrap contract and so bundle upload won't be handled unless you implemented it in your contract (Which you've uploaded in `cluster-create`) yourself.

**Comment by lathanbritz** [comment]
Im confused so the contract has been uploaded then to all the nodes and is running?

**Comment by lathanbritz** [comment]
I was confused i thought i still had to go an deploy the thing and it was only "claiming the cluster" seems i finally got it working to night!

congrats guys and girls!! its running for me
