### ISSUE TITLE
hpdevkit: Show more console.log outputs w/ `hpdevkit logs` command

### ISSUE THREAD

**Issue by wojake** [EvernodeXRPL/evernode-sdk#80]
#### hpdevkit 
<img width="522" alt="image" src="https://github.com/EvernodeXRPL/evernode-sdk/assets/87929946/20a1ac14-59cf-4721-b960-e3b89dab63df">

As of now, It's limited to 5 lines. Maybe expand it to 20 lines for us to be able to retrace back what had actually happened?

**Comment by ravinsp** [comment]
@wojake All hotpocket instances in hpdevkit are docker containers. So you can use docker commands to get log outputs as you want (`docker ps -a` would show you all docker containers in your pc).

For example, `docker logs hpdevkit_default_node_1 --tail=100 -f` would attach to logs while displaying previous 100 log lines.

**Comment by wojake** [comment]
I see, thank you!
