### ISSUE TITLE
hpdevkit: Contract file compilation fails if code is invalid

### ISSUE THREAD

**Issue by wojake** [EvernodeXRPL/evernode-sdk#85]
File compilation fails if the dApp's code is invalid.

For example:

`require(...)`  in the contract code would invalidate the file compilation process.

**Comment by ravinsp** [comment]
@wojake this is not clear. For one thing, the npm build SHOULD fail if the contract code is invalid. `require()` shouldn't cause any build failures unless you have specified an incorrect npm module path in the require.
Can you elaborate? probably I'm missing the meaning of your question.

**Comment by wojake** [comment]
Yes, you're right that it should fail but it should also end the execution & exit. The file compilation just freezes and I have to terminate that cmd session/window.
